- name: symlink dotfiles
  command: "stow {{ item }} -t /home/{{ ansible_user }}"
  args:
    chdir: "/home/{{ ansible_user }}/dotfile_source/.stow-targets"
  loop:
    - btop
    - hypr
    - kitty
    - mako
    - waybar
    - wlogout
    - wofi
  become: false
  register: stow_dotfiles
  changed_when: "'LINK' in stow_dotfiles.stdout or 'RESTOW' in stow_dotfiles.stdout or 'DELETE' in stow_dotfiles.stdout"
  failed_when: "'conflicts with existing target' in stow_dotfiles.stderr and not 'restow' in stow_dotfiles.stdout"

- name: ensure scripts are executable
  file:
    path: "{{ item }}"
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: false
  loop: "{{ lookup('file', '/home/{{ ansible_user }}/dotfile_source/**/*.sh', wantlist=True) }}"

